server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admindb?createDatabaseIfNotExist=true
    username: root
    password: Root@123Mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true