server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountdb?createDatabaseIfNotExist=true
    username: root
    password: Root@123Mysql
    hibernate:
      ddl-auto: update
    show-sql: true
