package com.example.account_service.dto;

import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import com.example.account_service.entity.AccountStatus;
import com.example.account_service.entity.AccountType;
import com.fasterxml.jackson.annotation.JsonFormat;
import jakarta.validation.constraints.*;

@Data
public class UsaAccountRequest {
    
    // Common System Fields (Auto-populated by frontend)
    @NotBlank
    private String userId;
    private String accountNumber; // Generated by backend
    @NotBlank
    private String bank;
    @NotBlank
    private String branch;
    private String ifscCode;
    private AccountStatus status = AccountStatus.PENDING;
    
    // Personal Details Section
    @NotBlank
    @Size(min = 2, max = 100)
    private String fullName;
    
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate dob;
    
    @NotBlank
    @Pattern(regexp = "Male|Female|Other")
    private String gender;
    
    @NotBlank
    @Pattern(regexp = "^\\+1[0-9]{10}$")
    private String phone;
    
    @NotBlank
    @Email
    private String email;
    
    @NotBlank
    @Size(min = 10)
    private String address;
    
    @NotBlank
    @Pattern(regexp = "^[0-9]{3}-[0-9]{2}-[0-9]{4}$")
    private String ssn;
    
    // Educational Details Section
    @NotBlank
    @Pattern(regexp = "High School|Associate Degree|Bachelor Degree|Master Degree|Doctoral Degree")
    private String educationLevel;
    
    @NotBlank
    private String institutionName;
    
    @NotBlank
    private String course;
    
    @NotNull
    @Min(1950) @Max(2030)
    private Integer yearOfCompletion;
    
    private String grade; // Optional
    
    // Income Details Section
    @NotBlank
    @Pattern(regexp = "Employed|Self-Employed|Business Owner|Student|Retired|Unemployed")
    private String employmentStatus;
    
    private String employerName; // Optional
    
    @NotBlank
    private String occupation;
    
    @NotNull
    @DecimalMin("0.0")
    private BigDecimal monthlyIncome;
    
    @NotNull
    @DecimalMin("0.0")
    private BigDecimal annualIncome;
    
    @NotBlank
    @Pattern(regexp = "Salary|Business|Investment|Social Security|Other")
    private String incomeSource;
    
    // Nominee Details Section
    @NotBlank
    private String nomineeName;
    
    @NotBlank
    @Pattern(regexp = "Spouse|Father|Mother|Son|Daughter|Brother|Sister|Other")
    private String nomineeRelation;
    
    @NotNull
    @JsonFormat(pattern = "yyyy-MM-dd")
    private LocalDate nomineeDob;
    
    @NotBlank
    @Pattern(regexp = "^\\+1[0-9]{10}$")
    private String nomineeContact;
    
    @NotBlank
    private String nomineeAddress;
    
    // Account Details
    @NotNull
    private AccountType accountType;
    
    @NotNull
    @DecimalMin("0.0")
    private BigDecimal deposit;
    
    @NotNull
    @AssertTrue
    private Boolean consent;
}
