spring.application.name=api-gateway
server.port=8080
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
spring.cloud.gateway.server.webmvc.routes[1].id=user-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/user/**
 
spring.cloud.gateway.server.webmvc.routes[2].id=account-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/accounts/**
 
spring.cloud.gateway.server.webmvc.routes[3].id=bank-service
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://BANK-SERVICE
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=/api/banks/**
 
spring.cloud.gateway.server.webmvc.routes[0].id=admin-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ADMIN-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/admin/**
 
spring.cloud.gateway.server.webmvc.routes[4].id=root-admin-service
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://ROOT-ADMIN-SERVICE
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/root/**