server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb?createDatabaseIfNotExist=true
    username: bankapp
    password: BankApp@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: noreplyinterbankinghub@gmail.com
    password: iwmrruyqugysrlwu
    properties:
      mail:
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
            protocols: "TLSv1.2"
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
        transport:
          protocol: smtp

jwt:
  secret: myVerySecretJWTKeyForBankingApplicationThatIsLongEnough
  expiration: 86400000 # 24 hours in milliseconds

