package com.example.account_service.entity;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;

import jakarta.persistence.*;
import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import lombok.*;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

@Entity
@Table(name = "accounts", indexes = {
    @Index(name = "idx_user_id", columnList = "userId"),
    @Index(name = "idx_account_number", columnList = "accountNumber"),
    @Index(name = "idx_status", columnList = "status"),
    @Index(name = "idx_country_status", columnList = "country, status")
})
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Account {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    // Common System Fields (Auto-populated by frontend)
    @NotBlank
    @Size(max = 50)
    @Column(name = "user_id", nullable = false, length = 50)
    private String userId;
    
    @Size(max = 20)
    @Column(name = "account_number", unique = true, length = 20)
    private String accountNumber; // Generated by backend
    
    @NotBlank
    @Size(max = 100)
    @Column(name = "bank", nullable = false, length = 100)
    private String bank;
    
    @NotBlank
    @Size(max = 100)
    @Column(name = "branch", nullable = false, length = 100)
    private String branch;
    
    @Size(max = 15)
    @Column(name = "ifsc_code", length = 15)
    private String ifscCode;
    
    @NotBlank
    @Pattern(regexp = "INDIA|USA|UK", message = "Country must be INDIA, USA, or UK")
    @Column(name = "country", nullable = false, length = 10)
    private String country;
    
    // Account Details
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "account_type", nullable = false)
    private AccountType accountType;
    
    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false)
    private AccountStatus status = AccountStatus.PENDING;
    
    @NotNull
    @DecimalMin(value = "0.0")
    @Digits(integer = 15, fraction = 2)
    @Column(name = "deposit_amount", nullable = false, precision = 15, scale = 2)
    private BigDecimal deposit;
    
    @NotNull
    @Column(name = "consent", nullable = false)
    private Boolean consent = false;
    
    // Application Progress Tracking
    @Enumerated(EnumType.STRING)
    @Column(name = "application_stage")
    private ApplicationStage applicationStage = ApplicationStage.PERSONAL;
    
    // Embedded Details - Auto-creates columns
    @Valid
    @Embedded
    private PersonalDetails personalDetails;
    
    @Valid
    @Embedded
    private EducationalDetails educationalDetails;
    
    @Valid
    @Embedded
    private IncomeDetails incomeDetails;
    
    @Valid
    @Embedded
    private NomineeDetails nomineeDetails;
    
    // Document References (One-to-Many)
    @OneToMany(mappedBy = "accountId", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    private List<DocumentMetadata> documents;
    
    // Audit Fields
    @CreationTimestamp
    @Column(name = "created_date", updatable = false)
    private LocalDateTime createdDate;
    
    @UpdateTimestamp
    @Column(name = "updated_date")
    private LocalDateTime updatedDate;
    
    @Size(max = 50)
    @Column(name = "created_by", length = 50)
    private String createdBy;
    
    public enum ApplicationStage {
        PERSONAL("Personal Details"),
        EDUCATIONAL("Educational Details"), 
        INCOME("Income Details"),
        NOMINEE("Nominee Details"),
        DOCUMENTS("Documents"),
        COMPLETE("Complete");
        
        private final String displayName;
        
        ApplicationStage(String displayName) {
            this.displayName = displayName;
        }
        
        public String getDisplayName() {
            return displayName;
        }
    }
}

